erreduarte
*** Found local files:
***   * /home/erreduarte/airflow/logs/dag_id=ELT_WB/run_id=manual__2024-09-27T18:10:33.034692+00:00/task_id=analysis_countries/attempt=2.log
[2024-09-27T19:13:22.279+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-27T19:13:22.337+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT_WB.analysis_countries manual__2024-09-27T18:10:33.034692+00:00 [queued]>
[2024-09-27T19:13:22.358+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT_WB.analysis_countries manual__2024-09-27T18:10:33.034692+00:00 [queued]>
[2024-09-27T19:13:22.359+0100] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-09-27T19:13:22.388+0100] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): analysis_countries> on 2024-09-27 18:10:33.034692+00:00
[2024-09-27T19:13:22.393+0100] {standard_task_runner.py:72} INFO - Started process 1199531 to run task
[2024-09-27T19:13:22.396+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'ELT_WB', 'analysis_countries', 'manual__2024-09-27T18:10:33.034692+00:00', '--job-id', '299', '--raw', '--subdir', 'DAGS_FOLDER/DAG_ELT_WB.py', '--cfg-path', '/tmp/tmp_qfkpqe2']
[2024-09-27T19:13:22.397+0100] {standard_task_runner.py:105} INFO - Job 299: Subtask analysis_countries
[2024-09-27T19:13:22.566+0100] {task_command.py:467} INFO - Running <TaskInstance: ELT_WB.analysis_countries manual__2024-09-27T18:10:33.034692+00:00 [running]> on host erreduarte
[2024-09-27T19:13:22.822+0100] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='renanduarte' AIRFLOW_CTX_DAG_ID='ELT_WB' AIRFLOW_CTX_TASK_ID='analysis_countries' AIRFLOW_CTX_EXECUTION_DATE='2024-09-27T18:10:33.034692+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-27T18:10:33.034692+00:00'
[2024-09-27T19:13:22.822+0100] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-27T19:13:22.874+0100] {base.py:84} INFO - Retrieving connection 'microsoft_azure_database'
[2024-09-27T19:13:23.337+0100] {logging_mixin.py:190} WARNING - /home/erreduarte/airflow/.venv/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py:303 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-09-27T19:13:23.552+0100] {python.py:240} INFO - Done. Returned value was: {'region': {0: 'SOUTH ASIA', 1: 'LATIN AMERICA AND CARIBBEAN', 2: 'AFRICA', 3: 'EAST ASIA AND PACIFIC', 4: 'EUROPE AND CENTRAL ASIA', 5: 'MIDDLE EAST AND NORTH AFRICA', 6: 'EASTERN AND SOUTHERN AFRICA', 7: 'AFRICA EAST', 8: 'WESTERN AND CENTRAL AFRICA', 9: 'AFRICA WEST'}, 'country': {0: 'INDIA', 1: 'BRAZIL', 2: 'CONGO DEMOCRATIC REPUBLIC OF', 3: 'THAILAND', 4: 'NETHERLANDS', 5: 'IRAQ', 6: 'CONGO DEMOCRATIC REPUBLIC OF', 7: 'CONGO DEMOCRATIC REPUBLIC OF', 8: 'COTE DIVOIRE', 9: 'COTE DIVOIRE'}, 'debt_remaining': {0: 6742879994.2, 1: 4033909741.61, 2: 3154303190.46, 3: 1264655096.6, 4: 1215230460.08, 5: 1047474619.94, 6: 824097229.94, 7: 596760063.06, 8: 11844553.52, 9: 8577090.48}}
[2024-09-27T19:13:23.648+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-27T19:13:23.648+0100] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ELT_WB, task_id=analysis_countries, run_id=manual__2024-09-27T18:10:33.034692+00:00, execution_date=20240927T181033, start_date=20240927T181322, end_date=20240927T181323
[2024-09-27T19:13:23.691+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-27T19:13:23.762+0100] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-27T19:13:23.765+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
